version = 0.1
[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "account-sync"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bmsnt3mdcru3"
s3_prefix = "account-sync"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
